apiVersion: apps/v1
kind: Deployment
metadata:
  name: resolution-api
  labels:
    app: resolution-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resolution-api
  template:
    metadata:
      labels:
        app: resolution-api
    spec:
      containers:
      - name: api-a
        # This image must be pushed to Docker Hub
        # Build: docker build -t user-api:1.0 ./api
        # Tag: docker tag user-api:1.0 <your-dockerhub-username>/user-api:1.0
        # Push: docker push <your-dockerhub-username>/user-api:1.0
        # Then update this line to: image: <your-dockerhub-username>/user-api:1.0
        image: yehudafreiman/resolution-api:3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: SERVICE_B_URL
            value: "http://storage-api:8001/"

