apiVersion: v1
kind: Service
metadata:
  name: resolution-api-svc
  labels:
    app: resolution-api
spec:
  selector:
    app: resolution-api
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000